
import 'package:flutter/material.dart';
import 'package:app/models/customer_model.dart';
import 'package:app/services/customer_service.dart';
import 'package:app/widgets/custom_button.dart';
import 'package:app/widgets/custom_text_field.dart';

class CustomerCreateScreen extends StatefulWidget {
  const CustomerCreateScreen({super.key});

  @override
  State<CustomerCreateScreen> createState() => _CustomerCreateScreenState();
}

class _CustomerCreateScreenState extends State<CustomerCreateScreen> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final _emailController = TextEditingController();
  final _phoneController = TextEditingController();
  final _notesController = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Create Customer'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Form(
          key: _formKey,
          child: Column(
            children: [
              CustomTextField(
                controller: _nameController,
                labelText: 'Customer Name',
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Please enter customer name';
                  }
                  return null;
                },
              ),
              CustomTextField(
                controller: _emailController,
                labelText: 'Email',
                keyboardType: TextInputType.emailAddress,
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Please enter email';
                  }
                  return null;
                },
              ),
              CustomTextField(
                controller: _phoneController,
                labelText: 'Phone',
                keyboardType: TextInputType.phone,
              ),
              CustomTextField(
                controller: _notesController,
                labelText: 'Notes',
                maxLines: 3,
              ),
              const SizedBox(height: 20),
              CustomButton(
                text: 'Create Customer',
                onPressed: () async {
                  if (_formKey.currentState!.validate()) {
                    final newCustomer = Customer(
                      id: '', // ID will be generated by the backend
                      name: _nameController.text,
                      email: _emailController.text,
                      phone: _phoneController.text,
                      notes: _notesController.text,
                    );

                    try {
                      await CustomerService().createCustomer(newCustomer);
                      ScaffoldMessenger.of(context).showSnackBar(
                        const SnackBar(content: Text('Customer created successfully')),
                      );
                      Navigator.pop(context);
                    } catch (e) {
                      ScaffoldMessenger.of(context).showSnackBar(
                        SnackBar(content: Text('Failed to create customer: ${e.toString()}')),
                      );
                    }
                  }
                },
              ),
            ],
          ),
        ),
      ),
    );
  }
}
